pub const RESULT_TASK_ID: &str = "RESULT_TASK_ID";
pub const RESULT_STORAGE_CALLBACK: &str = "RESULT_STORAGE_CALLBACK";
pub const RESULT_ENCRYPTION: &str = "RESULT_ENCRYPTION";
pub const RESULT_STORAGE_PROVIDER: &str = "RESULT_STORAGE_PROVIDER";
pub const RESULT_STORAGE_PROXY: &str = "RESULT_STORAGE_PROXY";
pub const RESULT_STORAGE_TOKEN: &str = "RESULT_STORAGE_TOKEN";
pub const RESULT_SIGN_WORKER_ADDRESS: &str = "RESULT_SIGN_WORKER_ADDRESS";
pub const RESULT_SIGN_TEE_CHALLENGE_PRIVATE_KEY: &str = "RESULT_SIGN_TEE_CHALLENGE_PRIVATE_KEY";
