pub mod util {
	// Constants for pre-compute phase
	pub const IEXEC_TASK_ID: &str = "IEXEC_TASK_ID";
	pub const IEXEC_PRE_COMPUTE_OUT: &str = "IEXEC_PRE_COMPUTE_OUT";
	pub const IS_DATASET_REQUIRED: &str = "IS_DATASET_REQUIRED";
	pub const IEXEC_DATASET_URL: &str = "IEXEC_DATASET_URL";
	pub const IEXEC_DATASET_KEY: &str = "IEXEC_DATASET_KEY";
	pub const IEXEC_DATASET_CHECKSUM: &str = "IEXEC_DATASET_CHECKSUM";
	pub const IEXEC_DATASET_FILENAME: &str = "IEXEC_DATASET_FILENAME";
	pub const IEXEC_INPUT_FILES_NUMBER: &str = "IEXEC_INPUT_FILES_NUMBER";
	pub const IEXEC_INPUT_FILE_URL_PREFIX: &str = "IEXEC_INPUT_FILE_URL_PREFIX";

	// Constants for app phase
	pub const IEXEC_BOT_FIRST_INDEX: &str = "IEXEC_BOT_FIRST_INDEX";
	pub const IEXEC_BOT_SIZE: &str = "IEXEC_BOT_SIZE";
	pub const IEXEC_BOT_TASK_INDEX: &str = "IEXEC_BOT_TASK_INDEX";
	pub const IEXEC_DATASET_ADDRESS: &str = "IEXEC_DATASET_ADDRESS";
	pub const IEXEC_IN: &str = "IEXEC_IN";
	pub const IEXEC_INPUT_FILES_FOLDER: &str = "IEXEC_INPUT_FILES_FOLDER";
	pub const IEXEC_OUT: &str = "IEXEC_OUT";

	// Constants for post-compute phase
	pub const RESULT_TASK_ID: &str = "RESULT_TASK_ID";
	pub const RESULT_STORAGE_CALLBACK: &str = "RESULT_STORAGE_CALLBACK";
	pub const RESULT_ENCRYPTION_PUBLIC_KEY: &str = "RESULT_ENCRYPTION_PUBLIC_KEY";
	pub const RESULT_STORAGE_PROVIDER: &str = "RESULT_STORAGE_PROVIDER";
	pub const RESULT_STORAGE_PROXY: &str = "RESULT_STORAGE_PROXY";
	pub const RESULT_STORAGE_TOKEN: &str = "RESULT_STORAGE_TOKEN";
	pub const RESULT_ENCRYPTION: &str = "RESULT_ENCRYPTION";
	pub const RESULT_SIGN_WORKER_ADDRESS: &str = "RESULT_SIGN_WORKER_ADDRESS";
	pub const RESULT_SIGN_TEE_CHALLENGE_PRIVATE_KEY: &str = "RESULT_SIGN_TEE_CHALLENGE_PRIVATE_KEY";
}
